// Environment variable name constants - single source of truth
export const ENV = {
  NODE_ENV: 'NODE_ENV',

  // API Gateway
  API_GATEWAY_PORT: 'API_GATEWAY_PORT',

  // Command Service
  COMMAND_SERVICE_HOST: 'COMMAND_SERVICE_HOST',
  COMMAND_SERVICE_PORT: 'COMMAND_SERVICE_PORT',

  // Query Service
  QUERY_SERVICE_HOST: 'QUERY_SERVICE_HOST',
  QUERY_SERVICE_PORT: 'QUERY_SERVICE_PORT',

  // Fraud Service
  FRAUD_SERVICE_HOST: 'FRAUD_SERVICE_HOST',
  FRAUD_SERVICE_PORT: 'FRAUD_SERVICE_PORT',

  // Write Database
  DB_WRITE_HOST: 'DB_WRITE_HOST',
  DB_WRITE_PORT: 'DB_WRITE_PORT',
  DB_WRITE_USERNAME: 'DB_WRITE_USERNAME',
  DB_WRITE_PASSWORD: 'DB_WRITE_PASSWORD',
  DB_WRITE_DATABASE: 'DB_WRITE_DATABASE',

  // Read Database
  DB_READ_HOST: 'DB_READ_HOST',
  DB_READ_PORT: 'DB_READ_PORT',
  DB_READ_USERNAME: 'DB_READ_USERNAME',
  DB_READ_PASSWORD: 'DB_READ_PASSWORD',
  DB_READ_DATABASE: 'DB_READ_DATABASE',

  // Fraud Database
  DB_FRAUD_HOST: 'DB_FRAUD_HOST',
  DB_FRAUD_PORT: 'DB_FRAUD_PORT',
  DB_FRAUD_USERNAME: 'DB_FRAUD_USERNAME',
  DB_FRAUD_PASSWORD: 'DB_FRAUD_PASSWORD',
  DB_FRAUD_DATABASE: 'DB_FRAUD_DATABASE',

  // RabbitMQ
  RABBITMQ_HOST: 'RABBITMQ_HOST',
  RABBITMQ_PORT: 'RABBITMQ_PORT',
  RABBITMQ_USER: 'RABBITMQ_USER',
  RABBITMQ_PASSWORD: 'RABBITMQ_PASSWORD',

  // Redis
  REDIS_HOST: 'REDIS_HOST',
  REDIS_PORT: 'REDIS_PORT',
} as const;

// Type for environment variable keys
export type EnvKey = (typeof ENV)[keyof typeof ENV];
